= Inspur Commit Kit
:toc:

[#synopsis]
== 用法

 inspurcommit [<操作>]

可选的操作有：amend, clean, diff, export, init, load, merge, purge, push, template。详见 <<operation, 操作>> 章节。

如果没有提供 _操作_，则此命令为用来提交代码，详见 <<commit, 代码的提交>> 章节。

[#init]
== 初始化

代码仓库初次使用该脚本时，需在 Git Bash 中执行以下命令进行初始化：

 inspurcommit init [<options>]

此动作是针对代码库进行的，每个代码库只需要初始化使用一次。只要有一位成员进行了初始化动作 _并上传_ 至 Gerrit，其他成员下载到的代码即是已初始化完成的，不需要再次进行初始化。

init 命令可以使用参数为模板对应字段设置默认值，如 `--tag EXAMPLE_TAG` 参数可将模板中 `Tag#` 字段内容设置为 `EXAMPLE_TAG`。参数详细信息及“初始化”所做的操作请见“操作”章节。

IMPORTANT: 为保证能正确导出提交历史，此后所有提交动作只能通过此脚本进行。

[#commit]
== 代码的提交

提交代码步骤：

. 在 Git Bash 中使用 https://git-scm.com/docs/git-add[git-add^] 添加将要提交的代码改动。
** 使用 `git add .` 添加当前目录下所有改动（注意末尾的 `.` ）。
** 使用 `git add <path>` 按文件名添加改动，可以使用通配符。
** 使用 `git add -u` 添加当前目录下的 _修改_ 和 _删除_ 改动，不添加新增的文件。
. 如果代码库里面没有文件 ChangeHistory.txt，使用一次命令 `inspurcommit` 会生成该文件。使用英文填写 ChangeHistory.txt 并保存。模板文件中的空行和以 `#` 开头的行将被忽略。
. 使用命令 `inspurcommit` 。如果给此命令提供了参数，它们将会被传递给 https://git-scm.com/docs/git-commit[git-commit^]。
. 若要把当前分支提交的改动上传至 Gerrit 对应分支，使用命令 `inspurcommit push` 。

TIP: ChangeHistoryTemplate.txt 文件的改动是无法被提交的，如需修改模板，使用命令 `inspurcommit template` 。

[#operation]
== 操作

amend:: 使用命令 `inspurcommit amend` 来改正上一个提交。用以下几个情况来举例说明使用方法。
+
--
* 模板文件填写有误
.. 修正 ChangeHistory.txt 文件，并保存
.. 执行命令 `inspurcommit amend`
.. 确认无误后执行命令 `inspurcommit push`
* 提交的代码内容有误
.. 修正有误的代码，并保存
.. 使用命令 `git add <文件路径>`
.. 如果需要更改 ChangeHistory.txt，更改并保存。
.. 使用命令 `inspurcommit amend`
.. 确认无误后执行命令 `inspurcommit push`
* 错误地提交了本不应提交的文件
.. 使用命令 `git restore -s HEAD^ -SW <文件路径>`
.. 使用命令 `inspurcommit amend`
.. 确认无误后执行命令 `inspurcommit push`
* 错误地提交了新文件
.. 删除错误提交的新文件
.. 使用命令 git add <文件路径>
.. 使用命令 inspurcommit amend。
.. 确认无误后执行命令 inspurcommit push
--
+
[TIP]
====
如果要撤消一次错误的 amend，使用如下命令：

 git reset --soft @{1}

====
+
TIP: 如果待改正的提交包含模板的改动，应使用 `amendtemplate` 操作。

amendtemplate:: 如果待改正的提交包含模板的改动，需要使用此操作。除此之外与 `amend` 相同。

clean:: 清理代码中被 override 的文件。

commit:: 此为默认操作，详见 <<commit, 代码的提交>>。

diff:: 使用 Beyond Compare 对比当前改动。如果提供了参数，它们会被传递给 https://git-scm.com/docs/git-difftool[git-difftool^]。如果要对比已添加（staged）的改动，使用如下命令：
+
 inspurcommit diff --cached

export::
+
 inspurcommit export [-a|--all] [{-x|--exclude} <filter>,...] [--] [<filename>]
+
导出一份 change-history 到 `ChangeHistory-<hash>.txt`，`<hash>` 表示当前 commit ID，不包含 _scope_ 字段（除非使用了 `--all` 参数）。
+
如果指定了 --exclude <filter> 参数，则包含 _scope_ 字段，但会排除所有指定的 <filter>。多个 <filter> 用英文逗号 (`,`) 分隔。如 `-x tag#,scope` 。
+
TIP: `--exclude` 隐含 `--all` 。

init:: 当一个代码仓库开始使用此脚本提交之前，需要用一次 `inspurcommit init` 命令以标示一个临界点，未来使用 export 或 exportall 操作进行导出时，将只会导出此临界点之后的提交历史。
+
此操作支持以下参数：
+
 -t, --tag <tag#>
 -l, --label <label#>
 -i, --issue <Issue#>
 -s, --scope <Scope>
 -v, --severity <Severity>
 -c, --category <Category>
 -y, --symptom <Symptom>
 -r, --rootcause <RootCause>
 -o, --solution <Solution>
 -d, --dependency <SolutionDependency>
 -f, --files <RelatedFiles>
+
例如，
+
 inspurcommit init -t "5.19_CedarIslandCrb_0ACMT_013" -d "None"
+
上述命令会将模板的 tag# 设为 5.19_CedarIslandCrb_0ACMT_013，将 SolutionDependency 设为 None。
+
[TIP]
====
初始化会做以下操作：

. 将 ChangeHistory.txt 重命名为 OldChangeHistory.txt
. 将默认模板放入代码库根目录，如果提供了参数，则根据参数修改模板
. 将临界点 commit ID 写入文件 farewell-commit-id
. 将 /ChangeHistory.txt 和 /ChangeHistory-*.txt 加入 .gitignore
. 提交上述改动，生成一条标题为 INSPURCOMMIT-INIT 的 commit
====

load:: 从指定的 commit 载入 message 内容到 ChangeHistory.txt，如果没有指定 commit，则从当前的 commit 载入。

merge:: 使用 Beyond Compare 解决合并时的冲突。如果要解决指定文件的冲突，在后面加上文件名。

purge:: 移除并重新生成一份 ChangeHistory.txt。

push::
+
 inspurcommit push [<options> ...] [<branch>]
+
将本地提交推送至 Gerrit 的同名分支。如果提供了 <options>，它们将会被传递给 https://git-scm.com/docs/git-push[git-push^]。 如果指定了 <branch>，则推送到 Gerrit 的此分支。

template:: 默认情况下提交码时如果包含了模板文件，脚本会自动排除它但仍然提交其余改动。如果要修改模板并提交，需要使用 `template` 操作。
